config/routes.rb
Rails.application.routes.draw do
#   devise_for :companies, controllers: {
#     sessions: 'companies/sessions',
#     passwords: 'companies/passwords',
#     registrations: 'companies/registrations'
# }
#   devise_for :users, controllers: {
#     sessions: 'users/sessions',
#     passwords: 'users/passwords',
#     registrations: 'users/registrations'
# }

  devise_for :companies, skip: [:registrations]
  as :company do
    get 'companies/edit' => 'companies/registrations#edit', :as => 'edit_company_registration'
    put 'companies' => 'companies/registrations#update', :as => 'company_registration'
  end

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  resources :users,           only: [:new, :create, :update]
  get 'profile',              to: 'users#show'
  get 'profile/edit',         to: 'users#edit'

  get 'new_author',           to: 'users#new_author'
  post 'generate_author',     to: 'users#generate_author'
  get 'new_student',          to: 'users#new_student'
  post 'generate_student',    to: 'users#generate_student'

  resources :companies,       only: [:new, :create, :update]
  get 'company/profile',      to: 'companies#show'
  get 'company/profile/edit', to: 'companies#edit'
  get "company/:user_id",     to: "companies#user_details", as: :company_user
  get "company_dashboard",    to: "companies#company_dashboard"

  resources :topics
  resources :categories
  resources :professions
  resources :temporary_user_credentials, only: [:new, :create, :show] do
    get "send_temp_user_credentials"
  end

  resources :articles do
    member do
      post  "read"
      get   "read_next"
      post   "read_next"
      # TODO! remove unread - just for testing
      # patch "unread"
      post  "bookmark"
      patch "unbookmark"
      post  "publish"
      patch "unpublish"
      get "flashcards"
    end

    resources :flashcards, only: :show do
      member do
        post "answer_multiple_choice", to: "flashcards#answer_multiple_choice"
        post "answer_correct_order",   to: "flashcards#answer_correct_order"
        post "answer_match",           to: "flashcards#answer_match"
        post "soll_ist",               to: "flashcards#soll_ist"
        get  "next_flashcard",         to: "flashcards#next_flashcard"
        post  "publish"
        patch "unpublish"
      end
    end
    get "quiz_results", to: "flashcards#results"
  end

  resources :flashcards, except: :show

  get "add_exam_categories", to: "custom_exams#add_exam_categories"
  get "add_exam_articles",   to: "custom_exams#add_exam_articles"

  resources :custom_exams, only: [:new, :create, :show], path: "exams" do
    get "results",      to: "custom_exams#results"
    get "submit_exam",  to: "custom_exams#submit_exam"
    get "info",         to: "pages#exam_info"

    resources :flashcards, only: :show do
      member do
        post "answer_multiple_choice", to: "flashcards#answer_multiple_choice"
        post "answer_correct_order",   to: "flashcards#answer_correct_order"
        post "answer_match",           to: "flashcards#answer_match"
        post "soll_ist",               to: "flashcards#soll_ist"
        post  "bookmark",              to: "flashcards#bookmark"
        patch "unbookmark",            to: "flashcards#unbookmark"
      end
    end
  end

  get "welcome",            to: "pages#welcome"
  get "dashboard",          to: "pages#dashboard"
  get "author_dashboard",   to: "pages#author_dashboard"
  get "admin_dashboard",    to: "pages#admin_dashboard"
  get "admin_professions",  to: "pages#admin_professions"
  get "admin_topics",       to: "pages#admin_topics"
  get "admin_categories",   to: "pages#admin_categories"
  get "search",             to: "pages#search"
  get "temp_user_success",  to: "pages#temporary_user_info"

  get "mozubi",             to: "pages#mozubi"
  get "azubis",             to: "pages#azubis"
  get "unternehmen",        to: "pages#unternehmen"
  get "datenschutz",        to: "pages#datenschutz"
  get "agbs",               to: "pages#agbs"
  get "impressum",          to: "pages#impressum"
  get "hilfspaket",         to: "pages#hilfspaket"


  root to: "pages#landing_page"
end

app/models/article.rb
# Term
class Article < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:title]

  before_save :ensure_published_at, :unless => :draft

  belongs_to        :category
  has_many          :chapters, dependent: :destroy
  has_many          :user_articles, dependent: :destroy
  has_many          :users, through: :user_articles
  has_many          :flashcards, dependent: :destroy
  has_many          :flashcard_queues

  has_one_attached  :image
  has_rich_text     :description
  has_rich_text     :content

  accepts_nested_attributes_for :chapters,
                                allow_destroy: true,
                                reject_if: proc { |att| att['title'].blank? }

  validates :title, presence: true, allow_blank: false
  validates :category_id, presence: true
  validates :image, content_type: {
                      in: %w[image/jpeg image/gif image/png],
                      message: "must be a valid image format"
                    },
                    size: {
                      less_than: 5.megabytes,
                      message:   "should be less than 5MB"
                    }

  # Scopes
  scope :draft,     -> { where(draft: true) }
  scope :published, -> { where(draft: false) }

  def read_for?(user)
    UserArticle.where(user: user, article: self, read: true).present?
  end

  def read_for!(user)
    UserArticle.find_or_create_by(user: user, article: self).update(read: true)
  end

  def unread_for!(user)
    UserArticle.where(user: user, article: self).update(read: false)
  end

  def bookmarked_for?(user)
    UserArticle.where(user: user, article: self, bookmarked: true).present?
  end

  def bookmark_for!(user)
    UserArticle.find_or_create_by(user: user, article: self).update(bookmarked: true)
  end

  def unbookmark_for!(user)
    UserArticle.where(user: user, article: self).update(bookmarked: false)
  end

  # Set article author
  def sign_article!(user)
    UserArticle.find_or_create_by(user: user, article: self).update(author: true)
  end

  def authored_by?(user)
    UserArticle.where(user: user, article: self, author: true).present?
  end

  def main_author
    User.joins(:user_articles).find_by(user_articles: { author: true,
                                                      article: self })
  end

  def edited_by?(user)
    UserArticle.where(user: user, article: self, editor: true).present?
  end

  def sign_edit_article!(user)
    UserArticle.find_or_create_by(user: user, article: self).update(editor: true)
  end

  def editors
    User.joins(:user_articles).where(user_articles: { editor: true,
                                                      article: self })
  end

  def publish!
    self.draft = false
    self.save
  end

  def unpublish!
    self.update(draft: true, published_at: nil)
  end

  protected

  def ensure_published_at
    self.published_at ||= Time.zone.now
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, except: [:index, :new, :create]
  before_action :set_all, only: [:show, :read_next]

  def index
    authorize Article.new
    @upcoming_articles = policy_scope(Article)
    @bookmarked_articles = current_user.bookmarked_articles
    @read_articles = current_user.read_articles
    @topics = policy_scope(Topic)

    # Author view
    @all_articles = current_user.all_articles
    @topics = current_user.profession.topics
    @categories = current_user.all_categories

    # Render views for student or author
    render current_user.student? ? 'articles/index' : 'articles/author_index'
  end

  def show
    @flashcards_queue = FlashcardQueue.init_flashcards_queue(current_user, @article)
  end

  def new
    @article = Article.new
    authorize @article
    @categories = current_user.all_categories
  end

  def create
    @new_article = Article.new
    authorize @new_article
    @categories = current_user.all_categories
    # chapter_params = article_params[:chapters_attributes]
    @article = Article.new(article_params)
    if @article.save
      # raise
      @article.sign_article!(current_user)
      redirect_to edit_article_path(@article), notice: "Article created!"
    else
      render :new
    end
  end

  def edit
    @article.chapters.build([
      { title: "Erläuterung" },
      { title: "Praxisbeispiel aus der Wirtschaft" },
      { title: "Verwandte Themen" },
      ]) if @article.chapters.empty?
    @categories = current_user.all_categories
  end

  def update
    if @article.update(article_params)
      @article.sign_edit_article!(current_user)
      redirect_to @article, notice: "Article updated!"
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_back(fallback_location: admin_dashboard_path)
  end

  def read
    @article.read_for!(current_user)
    redirect_to @article
  end

  def unread
    @article.unread_for!(current_user)
    redirect_to @article
  end

  def bookmark
    @article.bookmark_for!(current_user)
    @article.read_for!(current_user) unless @article.read_for?(current_user)

    redirect_to @article
  end

  def unbookmark
    @article.unbookmark_for!(current_user)
    redirect_to @article
  end

  def publish
    @article.publish!
    redirect_back(fallback_location: @article)
  end

  def unpublish
    @article.unpublish!
    redirect_back(fallback_location: @article)
  end

  def flashcards
  end

  def read_next
    if @upcoming_articles.empty?
      @next_article = current_user.profession
                                  .topics.first
                                  .categories.first
                                  .articles.first
    elsif (@upcoming_articles & @category.articles).without(@article) != [] && @next_article = (@upcoming_articles & @category.articles).select{|a| a.id > @article.id} != []
      @next_article = (@upcoming_articles & @category.articles).select{|a| a.id > @article.id}.first
    elsif @topic.categories.select { |c| c.id > @category.id }.select { |c| c.articles & @upcoming_articles } != [] && @topic.categories.select { |c| c.id > @category.id }.select { |c| c.articles & @upcoming_articles }.first.articles.select { |a| @upcoming_articles.include?(a) } != []
      @next_article = @topic.categories.select { |c| c.id > @category.id }.select { |c| c.articles & @upcoming_articles }.first.articles.select { |a| @upcoming_articles.include?(a) }.first
    elsif @topics.select { |t| t.id > @topic.id }.select { |t| t.categories.each { |c| c.articles & @upcoming_articles } } != [] && @topics.select { |t| t.id > @topic.id }.select { |t| t.categories.each { |c| c.articles & @upcoming_articles } }.first.categories.select { |c| c.articles & @upcoming_articles } != [] && @topics.select { |t| t.id > @topic.id }.select { |t| t.categories.each { |c| c.articles & @upcoming_articles } }.first.categories.select { |c| c.articles & @upcoming_articles }.first.articles != [] && @topics.select { |t| t.id > @topic.id }.select { |t| t.categories.each { |c| c.articles & @upcoming_articles } }.first.categories.select { |c| c.articles & @upcoming_articles }.first.articles.select { |a| @upcoming_articles.include?(a) } != []
      @next_article = @topics.select { |t| t.id > @topic.id }.select { |t| t.categories.each { |c| c.articles & @upcoming_articles } }.first.categories.select { |c| c.articles & @upcoming_articles }.first.articles.select { |a| @upcoming_articles.include?(a) }.first
    elsif @topics.select { |t| t.id < @topic.id }.select { |t| t.categories.each { |c| c.articles & @upcoming_articles } } != [] && @topics.select { |t| t.id < @topic.id }.select { |t| t.categories.each { |c| c.articles & @upcoming_articles } }.first.categories.select { |c| c.articles & @upcoming_articles } != [] && @topics.select { |t| t.id < @topic.id }.select { |t| t.categories.each { |c| c.articles & @upcoming_articles } }.first.categories.select { |c| c.articles & @upcoming_articles }.first.articles !=[] && @topics.select { |t| t.id < @topic.id }.select { |t| t.categories.each { |c| c.articles & @upcoming_articles } }.first.categories.select { |c| c.articles & @upcoming_articles }.first.articles.select { |a| @upcoming_articles.include?(a) } != []
      @next_article = @topics.select { |t| t.id < @topic.id }.select { |t| t.categories.each { |c| c.articles & @upcoming_articles } }.first.categories.select { |c| c.articles & @upcoming_articles }.first.articles.select { |a| @upcoming_articles.include?(a) }.first
    else
      @next_article = @upcoming_articles.first
    end

    @article.read_for!(current_user)
    redirect_to @next_article
  end

  private

  # TODO! REFACTOR
  def set_all
    if current_user.student? || current_user.author?
    # @flashcard = @article.flashcards.published.first
    @categories = current_user.all_categories
    @category = @categories.find(@article.category_id)
    @topics = current_user.profession.topics
    @topic = @topics.find(@category.topic_id)
    @articles = current_user.all_articles.published
    @read_articles = current_user.read_articles.published
    @bookmarked_articles = current_user.bookmarked_articles.published
    @upcoming_articles = @articles - @read_articles
    end
  end

  def set_article
    @article = Article.find(params[:id])
    authorize @article
  end

  def article_params
    params.require(:article).permit(:category_id,
                                    :image,
                                    :title,
                                    :description,
                                    chapters_attributes: [:id, :_destroy, :title, :content])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<li id="article-<%= article.id %>%">
  <h4><%= link_to article.title, article %></h4>
  <p><%= article.description %></p>
</li>

app/views/articles/_author_article_list.html.erb
<li class="list-group-item d-flex">
  <%= link_to "#{article_counter+1}. #{article.title}",
              article %>
  <%= link_to "Bearbeiten",
              edit_article_path(article),
              class: "btn btn-warning",
              style: "margin-left: auto;" %>
  <%= link_to "Quiz bearbeiten",
              flashcards_article_path(article),
              class: "btn btn-info ml-2" %>
  <% if article.draft? %>
    <%= link_to 'Artikel veröffentlichen', publish_article_path(article),
                                    method: :post,
                                    class: "btn btn-success ml-2" %>
  <% else %>
    <%= link_to 'Artikel nicht veröffentlichen', unpublish_article_path(article),                                            method: :patch,
                                                 class: "btn btn-danger ml-2" %>
  <% end %>

</li>

app/views/articles/_chapter_fields.html.erb
<div class="nested-fields">
  <div class="card mt-5">
    <div class="card-body">
      <div class="form-group">
        <%= f.text_field :title, placeholder: "Beispiel Titel", readonly: true, class: "form-control chapter-title-disabled"%>
      </div>
      <div class="form-group">
        <%#= f.label "Kapitel" %>
        <%= f.rich_text_area :content, placeholder: "Kapitel Inhalte eintragen..." %>
      </div>
    </div>
  </div>

  <%#= link_to_remove_association "Remove chapter", f, class: 'btn btn-primary btn-xs mt-1' %>
</div>

app/views/articles/_form.html.erb
<%= render "devise/shared/error_messages", resource: object %>
<%= form_with model: object, local: true, class: "new-article-form" do |f| %>
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">

          <div class="form-group mb-5">
            <%= f.label "Kategorie" %>
            <% if current_user.admin? %>
              <%= f.select "category_id",
                  options_for_select(
                    Category.all.map { |category| [category.title, category.id] },
                    @article.category ? @article.category.id : false # set categroy for edit
                  ), {}, { class: 'select2' } %>
            <% else %>
              <%= f.select "category_id",
                options_for_select(
                  @categories.map { |category| [category.title, category.id] },
                  @article.category ? @article.category.id : false # set categroy for edit
                ), {}, { class: 'select2' } %>
            <% end %>
          </div>

          <!--  Titel -->
          <div class="form-group mb-5">
            <%= f.label      "Titel", class: "mr-2" %>
            <%= f.text_field :title, class: "form-control" %>
          </div>

          <div class="form-group mb-5">
            <%= f.label     "Definition" %>
            <%= f.rich_text_area :description %>
            <%#= f.text_area :description, class: "form-control" %>
          </div>


          <div class="input-group mb-5" style="max-width: 400px;">
            <div class="input-group-prepend">
              <span class="input-group-text">Upload Foto</span>
            </div>
            <div class="custom-file">
              <%= f.file_field :image,
                                            class: "custom-file-input",
                                            lang: "de" %>
              <%= f.label :image,
                  "Wählen Sie die Datei aus",
                  class: "custom-file-label" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <% if @article.image.attached? %>
        <div class="col-md-5">
          <div class="article-photo">
            <!-- Button trigger modal -->
            <button type="button" class="article-image__thumb" data-toggle="modal" data-target="#ArticleImage">
              <%= cl_image_tag @article.image.key %>
            </button>
        </div>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col">
      <div class="chapters" id="chapter">
        <%= f.fields_for :chapters do |builder| %>
          <%= render 'chapter_fields', f: builder %>

        <% end %>
      </div>
    </div>
  </div>

  <div class="row my-5" style="max-width: 720px;
    justify-content: center;" >
    <div class="col col-md-6 d-flex flex-column align-content-center">
        <%#= link_to_add_association 'Add chapter',
                                f, :chapters,
                                class: 'btn btn-success my-2',
                                data: {
                                  association_insertion_node: '#chapter', association_insertion_method: :append
                                } if @article.persisted? %>


      <%= f.submit "Aktualisieren", class: "btn btn-primary" %>
      <%= link_to "Artikel ansehen", @article, class: "btn btn-warning mt-3" if @article.persisted? %>
    </div>
  </div>
<% end %>

<%  if @article.persisted?  %>
  <div class="row">
    <div class="col">
      <ul class="list-group">
      <li class="list-group-item list-group-item-success">
        Artikel im Dashboard veröffentlichen
      </li>
    </ul>
    </div>
  </div>
<% end %>

<% if @article.image.attached? %>
  <!-- Modal -->
  <div class="modal fade" id="ArticleImage" tabindex="-1" role="dialog" aria-labelledby="ArticleImage" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="img">
      <div class="modal-content">
        <%= cl_image_tag @article.image.key %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_grid_view.html.erb
<!-- topic tab -->
<div role="tabpanel" class="tab-pane active py-3" id="topic">
  <div class="row flex-row flex-nowrap">
    <% @all_articles.each do |all_article| %>
      <div class="col-lg-3">
        <%= link_to all_article do %>
          <div class="card">
            <div class="card-block">
              <%= all_article.title %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<!-- upcoming tab -->
<div role="tabpanel" class="tab-pane py-3 mh-100" id="upcoming">
  <div class="row">  
    <% @upcoming_articles.each do |upcoming_article| %>
      <div class="col-lg-3">
        <%= link_to upcoming_article do %>
          <div class="card">
            <div class="card-block">
              <%= upcoming_article.title %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<!-- bookmarked tab -->
<div role="tabpanel" class="tab-pane py-3 mh-100" id="bookmarked">
  <div class="row">
    <% @bookmarked_articles.each do |bookmarked_article| %>
      <div class="col-lg-3">
        <%= link_to bookmarked_article do %>
          <div class="card">
            <div class="card-block">
              <%= bookmarked_article.title %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<!-- read tab -->
<div role="tabpanel" class="tab-pane py-3 mh-100" id="read">
  <div class="row">  
    <% @read_articles.each do |read_article| %>
      <div class="col-lg-3">
        <%= link_to read_article do  %>
          <div class="card">
            <div class="card-block">
              <%= read_article.title %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/flashcards.html.erb
<div class="w-100 mt-3 mr-4">
  <%= link_to "Neues Quiz", new_flashcard_path, class: "btn btn-outline-success ml-3" %>
  <% if @article.flashcards.any? %>
      <%= render partial: "flashcards/author_flashcard_list_item", collection: @article.flashcards, as: :flashcard %>
  <% else %>
    <div class="col-6">
        <h2>The article has no flashcards.</h2>
      </div>
      <div class="col-3">
        <%= link_to "Quiz erstellen", new_flashcard_path, class: "btn btn-primary" %>
    </div>
    <% end %>
</div>

app/views/articles/index.html.erb
<div class="container-fluid py-3 h-100">
  <div class="row mh-100">
    <!-- article header -->
    <div class="row col-12 justify-content-between">
      <div class="py-3">
        <h3>Artikel</h3>
      </div>
      <div class="">Grid/List View</div>
    </div>
    <div class="col-12 mh-100">
      <!-- tabs -->
      <ul class="nav nav-tabs justify-content-center" role="tablist">
        <li role="presentation" class="nav-item">
          <a href="#topic" aria-controls="topic" role="tab" data-toggle="tab" class="nav-link active">
            Themen
          </a>
        </li>
        <li role="presentation" class="nav-item">
          <a href="#upcoming" aria-controls="upcoming" role="tab" data-toggle="tab" class="nav-link">
            Offen
          </a>
        </li>
        <li role="presentation" class="nav-item">
          <a href="#bookmarked" aria-controls="bookmarked" role="tab" data-toggle="tab" class="nav-link">
            Markiert
          </a>
        </li>
        <li role="presentation" class="nav-item">
          <a href="#read" aria-controls="read" role="tab" data-toggle="tab" class="nav-link">
            Gelesen
          </a>
        </li>
      </ul>
      <div class="tab-content mh-100">
        <%#= render 'list_view' %>
        <%#= render 'grid_view' %>
      </div>
    </div>
  </div>

<div class="container">
  <%#= link_to "All nested topics", topics_path, class: "btn btn-primary" %>

</div>

app/views/articles/new.html.erb
<div class="container mx-5">
  <div class="row">
    <div class="col col-md-10">
      <h1 class="my-5 display-4">Neuer Artikel</h1>
          <%= render "form", object: @article %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<% if current_user.student? %>
<div class="container">
    <div class="row my-3 pt-3 col-12 breadcrumbs ml-3">
      <%= link_to "Alle Lernfelder", topics_path %> &nbsp
      <div class="breadcrumb-arrow"> > </div> &nbsp
      <%= link_to @topic.name, @topic %> &nbsp
      <div class="breadcrumb-arrow"> > </div> &nbsp
      <%= link_to @category.title, @category %> &nbsp
      <div class="breadcrumb-arrow"> > </div> &nbsp
      <%= @article.title %>
    </div>
<% end %>
  <div class="row mt-3 d-flex justify-content-end">
    <!-- article -->
    <div class="col-12 col-lg-8">
      <div class="card w-100">
        <!-- article headline -->
        <div class="row justify-content-between">
          <div class="col-10 col-lg-11">
            <h3 class="heading-2 d-none d-lg-block">
              <%= @article.title %>
            </h3>
            <h5 class="heading-2 d-lg-none d-block">
              <%= @article.title %>
            </h5>
          </div>
          <% if current_user.student? %>
            <div class="col-2 col-lg-1 row mx-0 px-0 align-items-center">
                <% if @article.bookmarked_for?(current_user) %>
                  <%= link_to unbookmark_article_path(@article),                                 method: :patch,
                                                    class: "" do %>
                    <i class="material-icons-sharp bookmark-icon">bookmark</i>
                  <% end %>
                <% else %>
                  <%= link_to bookmark_article_path(@article),
                                                  method: :post,
                                                  class: "" do %>
                    <i class="material-icons-sharp bookmark-icon">bookmark_border</i>
                  <% end %>
                <% end %>
              </p>
            </div>
          <% end %>
        </div>
        <!-- article description -->
        <div class="row">
          <div class="col-12">
            <h4 class="heading-4 d-none d-lg-block">Definition</h4>
            <h6 class="heading-4 d-lg-none d-block">Definition</h6>
            <p><%= @article.description %></p>
          </div>
        </div>
        <!-- article image -->
        <div class="row">
          <% if @article.image.attached? %>
              <div class="col-md-5">
                <div class="article-photo">
                  <!-- Button trigger modal -->
                  <button type="button" class="article-image__thumb" data-toggle="modal" data-target="#ArticleImage">
                    <%= cl_image_tag @article.image.key %>
                  </button>
              </div>
            </div>
          <% end %>
        </div>
        <!-- article chapters -->
        <div class="row">
          <div class="col-12">
            <ul>
              <%= render @article.chapters.includes([:rich_text_content]).sort_by { |chap| chap.title } %>
            </ul>
          </div>
        </div>
      </div>
      <% if @article.image.attached? %>
        <!-- Modal -->
        <div class="modal fade" id="ArticleImage" tabindex="-1" role="dialog" aria-labelledby="ArticleImage" aria-hidden="true">
          <div class="modal-dialog modal-xl" role="img">
            <div class="modal-content">
              <%= cl_image_tag @article.image.key %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-12 col-lg-3">
      <% if @article.chapters != [] %>
        <div class="card col-12 d-none d-lg-block">
          <ul>
            <% @article.chapters.sort_by { |chap| chap.title }.each do |chap| %>
            <li><%= chap.title %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%# if !@article.read_for?(current_user) %>
      <% if current_user.student? %>
        <div class="card col-12 mt-3 card">
          <%= link_to "Nächster Artikel", read_next_article_path , class: "width-btn btn btn-outline-primary" %>
          <%#= link_to @next_article, class: "btn btn-outline-primary mt-2" do %>
            <%#= link_to "Nächster Artikel",
                  read_jump_next_article,
                  method: :post,
                  class: "btn btn-outline-primary mt-2"%>
          <%# end %>
          <%# raise %>
        </div>

      <%# end %>
        <% if @article.flashcards.published.any? %>
          <div class="card col-12 mt-3 quizcard">
          Bereit zum Quiz über <%= @article.title %>?
          <%= link_to "Quiz", article_flashcard_path(@article,  @flashcards_queue.dequeue!),
                              "data-turbolinks": false,
                              class: "btn btn-light my-2" %>
          </div>
        <% end %>
      <% end %>
      <!-- author -->
      <% if current_user.author? || current_user.admin? %>
        <div class="card mt-3">
          <h5 class="badge badge-success" style="max-width: 230px;">
            <%= @article.draft ? "Entwurf" : "Öffentlich" %>
          </h5>
          <h5 class="badge badge-primary" style="max-width: 230px;">
            <%= "#{(current_user.first_name.present? && @article.main_author) ? @article.main_author.first_name : 'Kein Author'}" %>
          </h5>
          <h5>Editors:</h5>
          <% @article.editors.each do |editor| %>
          <h5 class="badge badge-primary" style="max-width: 230px;">
            <%= editor.first_name %>
          </h5>
          <% end %>
      <% end %>
      <% if current_user.author? || current_user.admin? %>
        <div class="row">
          <div class="col mt-5">
            <% if @article.draft? %>
              <%= link_to  'Artikel veröffentlichen',
                            publish_article_path(@article),
                            method: :post,
                            class: "btn btn-success mb-2 w-100",
                            style: "max-width: 230px;" %>
            <% else %>
              <%= link_to 'Artikel nicht veröffentlichen',
                          unpublish_article_path(@article),
                          method: :patch,
                          class: "btn btn-danger mb-2 w-100",
                          style: "max-width: 230px;" %>
            <% end %>
            <%= link_to 'Artikel anpassen',
                        edit_article_path(@article),
                        class: "btn btn-warning mb-2 w-100",
                        style: "max-width: 230px;" %>
            <%= link_to 'Quiz anpassen',
                        flashcards_article_path(@article),
                        class: "btn btn-warning mb-2 w-100",
                        style: "max-width: 230px;" %>
        </div>
      <% end %>
        </div>
      </div>
    </div>
  </div>
</div>