config/routes.rb
Rails.application.routes.draw do
#   devise_for :companies, controllers: {
#     sessions: 'companies/sessions',
#     passwords: 'companies/passwords',
#     registrations: 'companies/registrations'
# }
#   devise_for :users, controllers: {
#     sessions: 'users/sessions',
#     passwords: 'users/passwords',
#     registrations: 'users/registrations'
# }

  devise_for :companies, skip: [:registrations]
  as :company do
    get 'companies/edit' => 'companies/registrations#edit', :as => 'edit_company_registration'
    put 'companies' => 'companies/registrations#update', :as => 'company_registration'
  end

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  resources :users,           only: [:new, :create, :update]
  get 'profile',              to: 'users#show'
  get 'profile/edit',         to: 'users#edit'

  get 'new_author',           to: 'users#new_author'
  post 'generate_author',     to: 'users#generate_author'
  get 'new_student',          to: 'users#new_student'
  post 'generate_student',    to: 'users#generate_student'

  resources :companies,       only: [:new, :create, :update]
  get 'company/profile',      to: 'companies#show'
  get 'company/profile/edit', to: 'companies#edit'
  get "company/:user_id",     to: "companies#user_details", as: :company_user
  get "company_dashboard",    to: "companies#company_dashboard"

  resources :topics
  resources :categories
  resources :professions
  resources :temporary_user_credentials, only: [:new, :create, :show] do
    get "send_temp_user_credentials"
  end

  resources :articles do
    member do
      post  "read"
      get   "read_next"
      post   "read_next"
      # TODO! remove unread - just for testing
      # patch "unread"
      post  "bookmark"
      patch "unbookmark"
      post  "publish"
      patch "unpublish"
      get "flashcards"
    end

    resources :flashcards, only: :show do
      member do
        post "answer_multiple_choice", to: "flashcards#answer_multiple_choice"
        post "answer_correct_order",   to: "flashcards#answer_correct_order"
        post "answer_match",           to: "flashcards#answer_match"
        post "soll_ist",               to: "flashcards#soll_ist"
        get  "next_flashcard",         to: "flashcards#next_flashcard"
        post  "publish"
        patch "unpublish"
      end
    end
    get "quiz_results", to: "flashcards#results"
  end

  resources :flashcards, except: :show

  get "add_exam_categories", to: "custom_exams#add_exam_categories"
  get "add_exam_articles",   to: "custom_exams#add_exam_articles"

  resources :custom_exams, only: [:new, :create, :show], path: "exams" do
    get "results",      to: "custom_exams#results"
    get "submit_exam",  to: "custom_exams#submit_exam"
    get "info",         to: "pages#exam_info"

    resources :flashcards, only: :show do
      member do
        post "answer_multiple_choice", to: "flashcards#answer_multiple_choice"
        post "answer_correct_order",   to: "flashcards#answer_correct_order"
        post "answer_match",           to: "flashcards#answer_match"
        post "soll_ist",               to: "flashcards#soll_ist"
        post  "bookmark",              to: "flashcards#bookmark"
        patch "unbookmark",            to: "flashcards#unbookmark"
      end
    end
  end

  get "welcome",            to: "pages#welcome"
  get "dashboard",          to: "pages#dashboard"
  get "author_dashboard",   to: "pages#author_dashboard"
  get "admin_dashboard",    to: "pages#admin_dashboard"
  get "admin_professions",  to: "pages#admin_professions"
  get "admin_topics",       to: "pages#admin_topics"
  get "admin_categories",   to: "pages#admin_categories"
  get "search",             to: "pages#search"
  get "temp_user_success",  to: "pages#temporary_user_info"

  get "mozubi",             to: "pages#mozubi"
  get "azubis",             to: "pages#azubis"
  get "unternehmen",        to: "pages#unternehmen"
  get "datenschutz",        to: "pages#datenschutz"
  get "agbs",               to: "pages#agbs"
  get "impressum",          to: "pages#impressum"
  get "hilfspaket",         to: "pages#hilfspaket"


  root to: "pages#landing_page"
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  include Accessible
  skip_before_action :check_user, except: [:new, :create]
  # prepend_before_action :require_no_authentication, only: [:cancel]
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  include Accessible
  skip_before_action :check_user, only: :destroy

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  before_action :authenticate_user!, except: :new_temp_user
  before_action :set_user, only: [:show, :edit, :update, :new_author, :generate_author]

  def new
    @user = User.new
    authorize current_user
  end

  def create
    @user = User.new
    @user_credentials = UserCredential.new
    authorize current_user

    company = Company.find_by(name: "Mozubi")
    profession = Profession.find_by(name: "Controlling")
    new_user_params = user_params
    new_user_params[:profession] = profession
    new_user_params[:company] = company
    new_admin = generate_admin(new_user_params)
    @user = User.new(new_admin)

    # Save credentials for printing
    new_admin_credentials = new_admin.except(:first_name, :last_name, :email)
    @user_credentials = UserCredential.new(new_admin_credentials.merge({ user: current_user }))

    if @user.save
      @user_credentials.save
      flash[:notice] = "Admin created."
      redirect_to admin_dashboard_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  def new_author
    authorize current_user, :create?
    @professions = Profession.all
  end

  def generate_author
    authorize current_user, :create?
    company = Company.find_by(name: "Mozubi")
    profession = Profession.find(author_params[:profession_id])
    new_authors_params = generate_authors(company,
      profession,
      author_params[:authors_number].to_i)

    if User.create(new_authors_params)
      flash[:notice] = "#{new_authors_params.size} #{"author".pluralize(new_authors_params)} created."

    # Save credentials for printing
    save_author_credentials(new_authors_params, current_user)

    redirect_to admin_dashboard_path
    end
  end

  def new_student
    authorize current_user, :create?
    @companies = Company.all
    @professions = Profession.all
  end

  def generate_student
    authorize current_user, :create?
    company = Company.find(student_params[:company_id])
    profession = Profession.find(student_params[:profession_id])
    new_students_params = generate_students(company,
      profession,
      student_params[:students_number].to_i)

    if User.create(new_students_params)
      flash[:notice] = "#{new_students_params.size} #{"student".pluralize(new_students_params)} created."

    # Save credentials for printing
    save_students_credentials(new_students_params, current_user)

    redirect_to admin_dashboard_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :birth_date, :exam_date, :email, :role)
  end

  def author_params
    params.permit(:profession_id, :authors_number)
  end

  def student_params
    params.permit(:company_id, :profession_id, :students_number)
  end

  def set_user
    @user = current_user
    authorize @user, :show?
  end
end

app/helpers/users_helper.rb
require "securerandom"

module UsersHelper
  # company, profession, first_name, last_name, email
  def generate_admin(attributes={})
    {
      username: "mozubi-#{SecureRandom.hex[0..10]}",
      password: SecureRandom.hex[0..10],
      company: attributes[:company],
      profession: attributes[:profession],
      first_name: attributes[:first_name],
      last_name: attributes[:last_name],
      email: attributes[:email],
      role: :admin
    }
  end

  # company should always be mozubi
  def generate_authors(company, profession, licences_num)
    (0...licences_num).to_a.map do |i|
       {
        username: "author-#{SecureRandom.hex[0..10]}",
        password: SecureRandom.hex[0..10],
        profession: profession,
        company: company,
        role: :author
      }
    end
  end

  def generate_students(company, profession, licences_num)
    (0...licences_num).to_a.map do |i|
       {
        username: "#{company.name.downcase}-#{SecureRandom.hex[0..10]}",
        password: SecureRandom.hex[0..10],
        profession: profession,
        company: company,
        role: :student
      }
    end
  end

  def save_author_credentials(authors, user)
    authors.each do |author|
      UserCredential.create({
        username: author[:username],
        password: author[:password],
        user: user,
        company: author[:company],
        profession: author[:profession],
        role: author[:role]
        })
    end
  end

  def save_students_credentials(students, user)
    students.each do |student|
      UserCredential.create!({
        username: student[:username],
        password: student[:password],
        user: user,
        company: student[:company],
        profession: student[:profession],
        role: student[:role]
        })
    end
  end

  def save_temporary_student_credentials(student)
    TemporaryUserCredential.create!({
      username: student[:username],
      password: student[:password],
      company: student[:company],
      profession: student[:profession],
      role: student[:role]
    })
  end
end

app/views/users/_generated_temp_user.html.erb
<tr>
  <th scope="row"><%= user_counter + 1 %></th>
  <td><%= user.username %></td>
  <td><%= user.password %></td>
  <td><%= user.another_profession.blank? ? user.profession.name : user.another_profession  %></td>
  <td><%= user.email %></td>
    <td style="min-width: 130px;">
      <%= link_to "Send Email",     temporary_user_credential_send_temp_user_credentials_path(user.id),
      class: "btn #{user.sent_credentials ? 'btn-danger' : 'btn-success'}" %>
    </td>
  <% if user.feedback %>
    <!-- Button trigger modal -->
    <td>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newTempUserFeedback">
        Feedback
      </button>
    </td>
  <% end %>
</tr>


<% if user.feedback %>
  <!-- Modal -->
  <div class="modal fade" id="newTempUserFeedback" tabindex="-1" role="dialog" aria-labelledby="newTempUserFeedbackLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="newTempUserFeedbackLabel">Feedback</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= user.feedback %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_generated_user.html.erb
<tr>
  <th scope="row"><%= user_counter + 1 %></th>
  <td><%= user.username %></td>
  <td><%= user.password %></td>
  <td><%= user.profession.name if user.author? || user.student? %></td>
  <td><%= user.company.name if user.student? %></td>
</tr>

app/views/users/edit.html.erb
<div class="container py-3">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2>Profil anpassen</h2>
      <%= form_with(model: @user, local: true) do |f| %>
        <%= render "devise/shared/error_messages", resource: @user %>
        <div class='form-group'>
          <%= f.label "Vorname" %>
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label "Nachname" %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <% if current_user.student? %>
          <div class='form-group'>
            <%= f.label "Datum der Abschlussprüfung" %>
            <%= f.date_field :exam_date, required: true, class: 'form-control' %>
            <small id="emailHelp" class="form-text text-muted">*notwendig</small>
          </div>
        <% end %>
        <div class='form-group'>
          <%= f.label :birth_date, 'Geburtsdatum' %>
          <%= f.date_field :birth_date, class: 'form-control' %>
        </div>
        <%= f.submit 'Aktualisieren', class: "btn btn-primary w-100" %>
      <% end %>


      <%= link_to "Passwort ändern", edit_user_registration_path, class: 'btn btn-warning mt-3 w-100' %>
      <% unless current_user.exam_date.nil? %>
        <%= link_to "Dashboard", dashboard_path, class: 'btn btn-success mt-3 w-100' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="alert-danger">
        <p class="p-3">
          The new user will be an admin!!!
        </p>
      </div>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-6">
      <%= form_with(model: @user, local: true) do |f| %>
        <%= render "devise/shared/error_messages", resource: @user %>
        <div class='form-group'>
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>

        <div class='form-group'>
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>

        <%= f.submit "Create admin!", class: "btn btn-primary w-100" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new_author.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h2 class="display-4">Generate authors</h2>
    </div>
  </div>

  <div class="row justify-content-center mt-5">
    <div class="col-6">
      <p class="lead">Selct profession and number of authors to generate.</p>
    </div>
  </div>

  <div class="row justify-content-center mt-5">
    <div class="col-6">
      <%= form_with url: generate_author_path,
                    local: true,
                    class: "form-inline" do |f| %>

        <div class="form-group">
          <%= f.label "Profession", class: "mr-2" %>
          <%= f.select "profession_id",
                options_for_select(
                  @professions.map { |profession| [profession.name, profession.id] }.select { |p| p[0] != "Controlling" }
                ), {}, { class: 'select2' } %>
        </div>


        <div class="form-group ml-5">
          <%= f.label :authors_number, class: "mr-2" %>
          <%= f.number_field :authors_number,
                            class: "form-control",
                            style: "width: 100px;" %>
        </div>

        <%= submit_tag "Generate", class: "btn btn-primary mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new_student.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h2 class="display-4">Generate Students</h2>
    </div>
  </div>

  <div class="row justify-content-center mt-5">
    <div class="col-6">
      <p class="lead">You will generate new students</p>
    </div>
  </div>

  <div class="row justify-content-center mt-5">
    <div class="col-6">
      <%= form_with url: generate_student_path,
                    local: true do |f| %>

        <div class="form-group">
          <%= f.label "Company", class: "mr-2" %>
          <%= f.select "company_id",
                options_for_select(
                  @companies.map { |company| [company.name, company.id] }
                ) %>
        </div>

        <div class="form-group">
          <%= f.label "Profession", class: "mr-2" %>
          <%= f.select "profession_id",
                options_for_select(
                  @professions.map { |profession| [profession.name, profession.id] }.select { |p| p[0] != "Controlling" }
                ), {}, { class: 'select2' } %>
        </div>


        <div class="form-group5">
          <%= f.label :students_number, class: "mr-2" %>
          <%= f.number_field :students_number,
                            class: "form-control",
                            style: "width: 100px;" %>
        </div>

        <%= submit_tag "Generate", class: "btn btn-primary mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<section class="edit-profile container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="text-center my-5">Profil Einstellungen</h2>
      <% if current_user.first_name.present? %>
        <h4 class="mb-2">
          <%="Benutzer Daten von #{current_user.first_name}" %>
        </h4>
      <% end %>
      <table class="table table-striped my-3">
        <tbody>
          <tr>
            <th scope="row">Vorname</th>
            <td>
              <%= current_user.first_name if current_user.first_name.present? %>
            </td>
          </tr>
          <tr>
            <th scope="row">Nachname</th>
            <td>
              <%= current_user.last_name if current_user.last_name.present? %>
            </td>
          <tr>
            <th scope="row">Email</th>
            <td>
              <%= current_user.email if current_user.email.present? %>
            </td>
          </tr>
              <tr>
            <th scope="row">Geburtsdatum</th>
            <td>
              <%= current_user.birth_date if current_user.birth_date.present? %>
            </td>
          </tr>
          <% if current_user.student? %>
            <tr>
              <th scope="row">Datum der Abschlussprüfung</th>
              <td>
                <%= current_user.exam_date.to_formatted_s(:long) if current_user.exam_date.present? %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="text-center">
        <%= link_to 'Profil anpassen', profile_edit_path, class: "btn btn-primary" %>
        <%= link_to "Passwort ändern", edit_user_registration_path, class: "btn btn-warning"%>
      </div>
    </div>
  </div>
</section>