config/routes.rb
Rails.application.routes.draw do
#   devise_for :companies, controllers: {
#     sessions: 'companies/sessions',
#     passwords: 'companies/passwords',
#     registrations: 'companies/registrations'
# }
#   devise_for :users, controllers: {
#     sessions: 'users/sessions',
#     passwords: 'users/passwords',
#     registrations: 'users/registrations'
# }

  devise_for :companies, skip: [:registrations]
  as :company do
    get 'companies/edit' => 'companies/registrations#edit', :as => 'edit_company_registration'
    put 'companies' => 'companies/registrations#update', :as => 'company_registration'
  end

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  resources :users,           only: [:new, :create, :update]
  get 'profile',              to: 'users#show'
  get 'profile/edit',         to: 'users#edit'

  get 'new_author',           to: 'users#new_author'
  post 'generate_author',     to: 'users#generate_author'
  get 'new_student',          to: 'users#new_student'
  post 'generate_student',    to: 'users#generate_student'

  resources :companies,       only: [:new, :create, :update]
  get 'company/profile',      to: 'companies#show'
  get 'company/profile/edit', to: 'companies#edit'
  get "company/:user_id",     to: "companies#user_details", as: :company_user
  get "company_dashboard",    to: "companies#company_dashboard"

  resources :topics
  resources :categories
  resources :professions
  resources :temporary_user_credentials, only: [:new, :create, :show] do
    get "send_temp_user_credentials"
  end

  resources :articles do
    member do
      post  "read"
      get   "read_next"
      post   "read_next"
      # TODO! remove unread - just for testing
      # patch "unread"
      post  "bookmark"
      patch "unbookmark"
      post  "publish"
      patch "unpublish"
      get "flashcards"
    end

    resources :flashcards, only: :show do
      member do
        post "answer_multiple_choice", to: "flashcards#answer_multiple_choice"
        post "answer_correct_order",   to: "flashcards#answer_correct_order"
        post "answer_match",           to: "flashcards#answer_match"
        post "soll_ist",               to: "flashcards#soll_ist"
        get  "next_flashcard",         to: "flashcards#next_flashcard"
        post  "publish"
        patch "unpublish"
      end
    end
    get "quiz_results", to: "flashcards#results"
  end

  resources :flashcards, except: :show

  get "add_exam_categories", to: "custom_exams#add_exam_categories"
  get "add_exam_articles",   to: "custom_exams#add_exam_articles"

  resources :custom_exams, only: [:new, :create, :show], path: "exams" do
    get "results",      to: "custom_exams#results"
    get "submit_exam",  to: "custom_exams#submit_exam"
    get "info",         to: "pages#exam_info"

    resources :flashcards, only: :show do
      member do
        post "answer_multiple_choice", to: "flashcards#answer_multiple_choice"
        post "answer_correct_order",   to: "flashcards#answer_correct_order"
        post "answer_match",           to: "flashcards#answer_match"
        post "soll_ist",               to: "flashcards#soll_ist"
        post  "bookmark",              to: "flashcards#bookmark"
        patch "unbookmark",            to: "flashcards#unbookmark"
      end
    end
  end

  get "welcome",            to: "pages#welcome"
  get "dashboard",          to: "pages#dashboard"
  get "author_dashboard",   to: "pages#author_dashboard"
  get "admin_dashboard",    to: "pages#admin_dashboard"
  get "admin_professions",  to: "pages#admin_professions"
  get "admin_topics",       to: "pages#admin_topics"
  get "admin_categories",   to: "pages#admin_categories"
  get "search",             to: "pages#search"
  get "temp_user_success",  to: "pages#temporary_user_info"

  get "mozubi",             to: "pages#mozubi"
  get "azubis",             to: "pages#azubis"
  get "unternehmen",        to: "pages#unternehmen"
  get "datenschutz",        to: "pages#datenschutz"
  get "agbs",               to: "pages#agbs"
  get "impressum",          to: "pages#impressum"
  get "hilfspaket",         to: "pages#hilfspaket"


  root to: "pages#landing_page"
end

app/views/shared/_corona_form.html.erb
<a class="typeform-share button" href="https://markbitter.typeform.com/to/lq9WLX" data-mode="popup" style="display:inline-block;text-decoration:none;background-color:#3CD598;color:white !important;cursor:pointer;font-family:Roboto,sans-serif;font-size:1rem;line-height:3rem;text-align:center;margin:0;height:3rem;padding:0px 33px;border-radius:7px;width:100%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-weight:bold;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;" data-submit-close-delay="2" target="_blank">Kostenfrei bei Mozubi anmelden </a> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm_share", b="https://embed.typeform.com/"; if(!gi.call(d,id)){ js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show" role="alert" style="z-index: 10000;">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_hilfspaket_form.html.erb
<a class="typeform-share button" href="https://markbitter.typeform.com/to/lq9WLX" data-mode="popup" style="display:inline-block;text-decoration:none;background-color:#3CD598;color:white !important;cursor:pointer;font-family:Roboto,sans-serif;font-size:1rem;line-height:3rem;text-align:center;margin:0;height:3rem;padding:0px 33px;border-radius:7px;width:100%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-weight:bold;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;" data-submit-close-delay="2" target="_blank">Kostenfrei bei Mozubi anmelden </a> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm_share", b="https://embed.typeform.com/"; if(!gi.call(d,id)){ js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script>

app/views/shared/_landing_footer.html.erb
<div class="row mx-0 py-4 footer justify-content-center w-100">
	<div class="row mx-0 col-12 justify-content-around">	
	  <div class="col-3 col-md-1">
	  	<div class="row"><strong>Mozubi</strong></div>
	  	<div class="row">
	  		<%= link_to "Über Uns", mozubi_path %>
	  	</div>
	  	<div class="row">
	  		<%= link_to "Hilfspaket", hilfspaket_path %>
	  	</div>
	  	<!-- <div class="row">
	  		<%#= link_to "Azubis", azubis_path %>
	  	</div>
	  	<div class="row">
	  		<%#= link_to "Unternehmen", unternehmen_path %>
	  	</div> -->
	  </div>
	  <div class="col-3 col-md-1">
	  	<div class="row"><strong>Rechtliches</strong></div>
	  	<div class="row">
	  		<%= link_to "Datenschutz", datenschutz_path %>
	  	</div>
	  	<!-- <div class="row">
	  		<%#= link_to "AGBs", agbs_path %>
	  	</div> -->
	  	<div class="row">
	  		<%= link_to "Impressum", impressum_path %>
	  	</div>
	  </div>
	  <!-- <div class="col-1">
	  	<div class="row"><strong>Kontakt</strong></div>
	  	<div class="row">info@mozubi.app</div>
	  	<div class="row"></div>
	  </div> -->
	</div>
	<div class="row col-10 col-lg-12 mx-0 py-2 d-flex justify-content-center">
		<div class="d-none d-lg-flex justify-content-center col-12 py-3">
			<%= image_tag "https://res.cloudinary.com/mozubi/image/upload/v1584558166/Mozubi/Logo/Mozubi-blue-green_jtidxd.png", class: 'logo-footer' %>
		</div>
		<div>
		© <%= Time.zone.now.year %> Privatwirtschaftliches Institut für digitale Bildung
		</div>
	</div>
</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? && !company_signed_in? %>
	<ul class="nav-pills nav-fill row mx-0 justify-content-between mb-0">
		<li class="nav-item col-10 col-md-8 search-form-control">
			<%= form_with url: search_path,
			                    local: true,
			                    method: :get,
			                    html: {
			                      class:"form-inline w-100" } do |f| %>
	        <%= f.text_field :query,
	          class: "form-control",
	          placeholder: "Suche nach einem Artikel oder Begriff...",
	          style: "width: 100%",
	          id: "autocompleteSearch"
	        %>
		    <button name="button" type="submit" class="btn btn-flat align-items-center justify-content-center d-none d-lg-flex">
		      <i class="fas fa-search"></i> &nbsp
		      <div>Suchen</div>
		    </button>
	        <%= submit_tag "Search", class: "btn btn-primary d-none" %>
	      <% end %>
		</li>
      	<li class="nav-item dropdown col-1 col-md-2 d-flex justify-content-center">
			<button type="button" class="btn btn-primary dropdown-toggle d-none d-lg-block" data-toggle="dropdown" id="navbarDropdown" aria-haspopup="true" aria-expanded="false">
		 		Profil <span class="caret"></span>
		 	</button>
		 	<button type="button" class="btn btn-primary dropdown-toggle d-lg-none d-block" data-toggle="dropdown" id="navbarDropdown" aria-haspopup="true" aria-expanded="false">
		 		<span class="caret"></span>
		 	</button>
	        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
		        <%= link_to "Einstellungen", profile_path, class: "landing-nav dropdown-item" %>
		        <%= link_to "Ausloggen", destroy_user_session_path, method: :delete, class: "landing-nav dropdown-item" %>
	        </div>
      	</li>
    </ul>
<% elsif company_signed_in? %>
	<ul class="nav nav-pills nav-fill">
        <li class="nav-item">
          <%= link_to "Profil", company_profile_path, class: "btn btn-primary" %>
        </li>
        <li class="nav-item">
          <%= link_to "Ausloggen", destroy_company_session_path, method: :delete, class: "btn btn-outline-primary" %>
        </li>
	</ul>
<% else %>
<div class="row justify-content-between py-3">
	<!-- left navbar logo -->
	<div class="col-6 col-md-8">
		<%= link_to root_path do %>
	  		<%= image_tag "https://res.cloudinary.com/mozubi/image/upload/v1584558166/Mozubi/Logo/Mozubi-blue-green_jtidxd.png", class: "logo" %>
	  	<% end %>
	</div>

	<!-- <div class="col-2 collapse navbar-collapse" id="navbarSupportedContent"> -->
	<div class="col-4 col-sm-3 col-md-2 align-self-center d-flex justify-content-end">
	    <ul class="navbar-nav mr-auto">
	      <!-- <li class="nav-item active">
	        <%#= link_to "Home", "#", class: "nav-link" %>
	      </li>
	      <li class="nav-item">
	        <%#= link_to "Messages", "#", class: "nav-link" %>
	      </li> -->
	      <li class="nav-item dropdown">
			<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" id="navbarDropdown" aria-haspopup="true" aria-expanded="false">

				Einloggen <span class="caret"></span>

			</button>
	        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
		        <%= link_to "Azubi", new_user_session_path, class: "landing-nav dropdown-item" %>
		        <%= link_to "Unternehmen", new_company_session_path, class: "landing-nav dropdown-item" %>
	        </div>
	      </li>
	    </ul>
	</div>
	<!-- </div> -->
<% end %>

app/views/shared/_old_corona_form.html.erb
<h2>Corona Lizenz anfordern</h2>
      <%= form_with(model: @user, local: true) do |f| %>
        <%#= render "devise/shared/error_messages", resource: @user %>
        <div class='form-group'>
          <%= f.label "Vorname" %>
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label "Nachname" %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
        <div class='form-group'>
        	<%= f.label :birth_date, 'Geburtsdatum' %>
        	<%= f.date_field :birth_date, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label "Ausbildungsberuf" %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label "Ausbildungsbetrieb" %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label "Berufsschule" %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
        <div class='form-group'>
			<%= f.label "Abschlussprüfungsdatum" %>
			<%= f.date_field :exam_date, required: true, class: 'form-control' %>
			<small id="emailHelp" class="form-text text-muted">*notwendig</small>
		</div>
        <div class='form-group'>
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <%= f.submit 'Absenden', class: "btn btn-primary w-100" %>
      <% end %>

app/views/shared/_reminder.html.erb
<div class="alert alert-warning m2 " role="alert">
	<%= message %>
</div>

app/views/shared/_sidebar.html.erb
<% if user_signed_in? && !company_signed_in? %>
  <ul class="nav flex-column text-center w-lg-100 pl-lg-3">
  <!-- <ul class="nav flex-column text-center w-100 pl-3"> -->
    <!-- Dashboard -->
    <% if current_user.author? %>
      <li class="nav-item my-2">
        <%= link_to author_dashboard_path, class: "side-link #{current_class?(dashboard_path)}" do %>
          <div class="row">
            <i class="material-icons-sharp sidebar-icon">home</i>
            <div class="sidebar-text d-none d-lg-block">Dashboard</div>
          </div>
        <% end %>
      </li>
      <!-- Author library -->
      <li class="nav-item my-2">
        <%= link_to articles_path, class: "side-link #{current_class?(articles_path)}" do %>
          <div class="row">
            <i class="material-icons-sharp sidebar-icon">menu_book</i>
            <div class="sidebar-text d-none d-lg-block">Bibilothek</div>
          </div>
        <% end %>
      </li>

       <li class="nav-item my-2">
        <%= link_to new_article_path, class: "side-link #{current_class?(new_article_path)}" do %>
          <div class="row">
            <i class="material-icons-sharp sidebar-icon">description</i>
            <div class="sidebar-text d-none d-lg-block">Neuer Artikel</div>
          </div>
        <% end %>
      </li>

       <li class="nav-item my-2">
        <%= link_to new_flashcard_path, class: "side-link #{current_class?(new_flashcard_path)}" do %>
          <div class="row">
            <i class="material-icons-sharp sidebar-icon">dynamic_feed</i>
            <div class="sidebar-text d-none d-lg-block">Neues Quiz</div>
          </div>
        <% end %>
      </li>
    <% end %>
    <% if current_user.student? %>
      <li class="nav-item my-2">
        <%= link_to dashboard_path, class: "side-link #{current_class?(dashboard_path)}" do %>
          <div class="row">
            <i class="material-icons-sharp sidebar-icon">home</i>
            <div class="sidebar-text d-none d-lg-block">Dashboard</div>
          </div>
        <% end %>
      </li>

      <!-- Article -->
      <li class="nav-item my-2">
        <%= link_to topics_path, class: "side-link #{current_class?(topics_path)} #{current_class?(categories_path)} #{current_class?(articles_path)}" do %>
          <div class="row">
            <i class="material-icons-sharp sidebar-icon">menu_book</i>
            <div class="sidebar-text d-none d-lg-block">Artikel</div>
          </div>
        <% end %>
      </li>

      <!-- Quiz -->
      <li class="nav-item my-2">
        <% if current_class?(custom_exams_path)=="active" || current_class?(articles_path)=="active" %>
          <%= link_to flashcards_path, class: "side-link" do %>
            <div class="row">
              <i class="material-icons-sharp sidebar-icon">dynamic_feed</i>
              <div class="sidebar-text d-none d-lg-block">Quiz</div>
            </div>
          <% end %>
        <% else %>
          <%= link_to flashcards_path, class: "side-link #{current_class?(flashcards_path)}" do %>
            <div class="row">
              <i class="material-icons-sharp sidebar-icon">dynamic_feed</i>
              <div class="sidebar-text d-none d-lg-block">Quiz</div>
            </div>
          <% end %>
        <% end %>
      </li>
      <!-- Exams -->
      <li class="nav-item my-2 d-none d-lg-block">
        <%= link_to new_custom_exam_path, class: "side-link #{current_class?(custom_exams_path)}" do %>
          <div class="row">
            <i class="material-icons-sharp sidebar-icon">description</i>
            <div class="sidebar-text d-none d-lg-block">Prüfungen</div>
          </div>
        <% end %>
      </li>
      <!-- Slack -->
      <li class="nav-item my-2">
        <div class="side-link"> 

        <%#= link_to "https://mozubi.slack.com/", class: "side-link" do %>
          <a class="row" target="_blank" rel="noopener noreferrer" href="https://mozubi.slack.com/">
            <i class="fab fa-slack sidebar-icon"></i>
            <div class="sidebar-text d-none d-lg-block">Forum</div>
          </a>
        </div>
        <%# end %>
      </li>
    <% end %>
    <% if current_user.admin? %>
      <li class="nav-item">
        <%= link_to "Users", admin_dashboard_path, class: "side-link #{current_class?(admin_dashboard_path)}" %>
      </li>
      <li class="nav-item">
        <%= link_to "Professisons", admin_professions_path, class: "side-link #{current_class?(admin_professions_path)}" %>
      </li>
    <% end %>

  <!-- Company Dashboard -->
  <% elsif company_signed_in? %>
    <li class="nav-item">
      <%= link_to "Dashboard", company_dashboard_path, class: "side-link" %>
    </li>
  </ul>
<% end %>