config/routes.rb
Rails.application.routes.draw do
#   devise_for :companies, controllers: {
#     sessions: 'companies/sessions',
#     passwords: 'companies/passwords',
#     registrations: 'companies/registrations'
# }
#   devise_for :users, controllers: {
#     sessions: 'users/sessions',
#     passwords: 'users/passwords',
#     registrations: 'users/registrations'
# }

  devise_for :companies, skip: [:registrations]
  as :company do
    get 'companies/edit' => 'companies/registrations#edit', :as => 'edit_company_registration'
    put 'companies' => 'companies/registrations#update', :as => 'company_registration'
  end

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  resources :users,           only: [:new, :create, :update]
  get 'profile',              to: 'users#show'
  get 'profile/edit',         to: 'users#edit'

  get 'new_author',           to: 'users#new_author'
  post 'generate_author',     to: 'users#generate_author'
  get 'new_student',          to: 'users#new_student'
  post 'generate_student',    to: 'users#generate_student'

  resources :companies,       only: [:new, :create, :update]
  get 'company/profile',      to: 'companies#show'
  get 'company/profile/edit', to: 'companies#edit'
  get "company/:user_id",     to: "companies#user_details", as: :company_user
  get "company_dashboard",    to: "companies#company_dashboard"

  resources :topics
  resources :categories
  resources :professions
  resources :temporary_user_credentials, only: [:new, :create, :show] do
    get "send_temp_user_credentials"
  end

  resources :articles do
    member do
      post  "read"
      get   "read_next"
      post   "read_next"
      # TODO! remove unread - just for testing
      # patch "unread"
      post  "bookmark"
      patch "unbookmark"
      post  "publish"
      patch "unpublish"
      get "flashcards"
    end

    resources :flashcards, only: :show do
      member do
        post "answer_multiple_choice", to: "flashcards#answer_multiple_choice"
        post "answer_correct_order",   to: "flashcards#answer_correct_order"
        post "answer_match",           to: "flashcards#answer_match"
        post "soll_ist",               to: "flashcards#soll_ist"
        get  "next_flashcard",         to: "flashcards#next_flashcard"
        post  "publish"
        patch "unpublish"
      end
    end
    get "quiz_results", to: "flashcards#results"
  end

  resources :flashcards, except: :show

  get "add_exam_categories", to: "custom_exams#add_exam_categories"
  get "add_exam_articles",   to: "custom_exams#add_exam_articles"

  resources :custom_exams, only: [:new, :create, :show], path: "exams" do
    get "results",      to: "custom_exams#results"
    get "submit_exam",  to: "custom_exams#submit_exam"
    get "info",         to: "pages#exam_info"

    resources :flashcards, only: :show do
      member do
        post "answer_multiple_choice", to: "flashcards#answer_multiple_choice"
        post "answer_correct_order",   to: "flashcards#answer_correct_order"
        post "answer_match",           to: "flashcards#answer_match"
        post "soll_ist",               to: "flashcards#soll_ist"
        post  "bookmark",              to: "flashcards#bookmark"
        patch "unbookmark",            to: "flashcards#unbookmark"
      end
    end
  end

  get "welcome",            to: "pages#welcome"
  get "dashboard",          to: "pages#dashboard"
  get "author_dashboard",   to: "pages#author_dashboard"
  get "admin_dashboard",    to: "pages#admin_dashboard"
  get "admin_professions",  to: "pages#admin_professions"
  get "admin_topics",       to: "pages#admin_topics"
  get "admin_categories",   to: "pages#admin_categories"
  get "search",             to: "pages#search"
  get "temp_user_success",  to: "pages#temporary_user_info"

  get "mozubi",             to: "pages#mozubi"
  get "azubis",             to: "pages#azubis"
  get "unternehmen",        to: "pages#unternehmen"
  get "datenschutz",        to: "pages#datenschutz"
  get "agbs",               to: "pages#agbs"
  get "impressum",          to: "pages#impressum"
  get "hilfspaket",         to: "pages#hilfspaket"


  root to: "pages#landing_page"
end

app/models/category.rb
# Module containing Terms
class Category < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:title]

  has_many    :articles, dependent: :destroy
  belongs_to  :topic

  validates :title, presence: true, allow_blank: false
  validates :description, presence: true, allow_blank: true
  validates :topic_id, presence: true

  def category_flashcards
    Flashcard.joins(:article).where(articles: {category: self})
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update]

  def show
    if current_user.student?
    @topics = current_user.profession.topics
    @topic = @topics.find(@category.topic_id)
    @articles = policy_scope(Article)
    @category = Category.find(params[:id])
    @category_articles = @articles.select { |a| a.category_id == @category.id }

    @read_articles = @category.articles.select { |a| current_user.read_articles.include?(a) }
    @upcoming_articles = @category.articles.select { |a| @read_articles.exclude?(a) }
    @bookmarked_articles = @category.articles.select { |a| current_user.bookmarked_articles.include?(a) }
    else
      @category = Category.find(params[:id])
      authorize @category
    end
  end

  def new
    @category = Category.new
    @topics = Topic.all
    authorize @category
  end

  def create
    @category = Category.new(category_params)
    # @topics = Topic.all
    # raise
    authorize @category

    if @category.save
      redirect_to admin_dashboard_path, notice: "Module created!"
    else
      render :new
    end

  end

  def edit
    @topics = Topic.all
  end

  def update
    @topics = Topic.all

    if @category.update(category_params)
      redirect_to admin_dashboard_path, notice: "Module updated!"
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    authorize @category
    @category.destroy
    redirect_back(fallback_location: @article)
  end

  private

  def category_params
    params.require(:category).permit(:title, :description, :topic_id)
  end

  def set_category
    @category = Category.find(params[:id])
    authorize @category
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_author_category.html.erb
<li class="list-group-item d-flex">
  <%= link_to category.title,
              category %>
  <%= link_to "Bearbeiten",
              edit_category_path(category),
              class: "btn btn-warning",
              style: "margin-left: auto;" %>
  <b>&nbsp;<%= category.topic.profession.name %></b>
</li>

app/views/categories/_form.html.erb
<%= render "devise/shared/error_messages", resource: object  %>
<%= form_with model: object, local: true do |f| %>

  <div class="form-group">
    <%= f.label "Topic:" %>
    <%= f.select "topic_id",
          options_for_select(
            @topics.map { |topic| [topic.name, topic.id] },
            @category.topic ? @category.topic.id : false # set topic for edit form
          ) , {}, { class: 'select2' } %>
  </div>

  <div class="form-group">
    <%= f.label "Titel" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= f.label "Definition" %>
  <%= f.text_area :description, class: "form-control" %>
  </div>

  <%= f.submit "Aktualisieren", class: "btn btn-primary" %>
<% end %>

app/views/categories/_grid_view.html.erb
<% if current_user.student? %>
<!-- topic tab -->
<div role="tabpanel" class="tab-pane active py-3" id="topic">
  <div class="row">
    <% @category.articles.published.each do |article| %>
      <div class="col-lg-3 my-2">
        <%= link_to article do %>
          <div class="card topic-card justify-content-between">
            <div class="card-name pt-1 pb-4">
              <%= article.title %>
            </div>
            <div class="card-bottom">
              <div class="card-progress">
                <div class="row mx-0 justify-content-between">
                  <div class="read-text">
                    Gelesen
                  </div>
                  <% if @read_articles.include?(article) %>
                    <div class="progress-percentage">
                      100%
                    </div>
                    <progress class="w-100" value="100" max="100"></progress>
                  <% else %>
                    <div class="progress-percentage">
                      0%
                    </div>
                    <progress class="w-100" value="0" max="100"></progress>
                  <% end %>
                </div>
              </div>
              <div class="card-stats row justify-content-between">
                <div class="read-articles row mx-0 align-items-center">
                  <i class="material-icons-sharp stats-icon p-1">library_books</i>
                  1
                  Artikel
                </div>
                <div class="reading-time row mx-0 align-items-center">
                  <i class="material-icons-sharp stats-icon p-1">access_time</i>
                    <%= 1 * 2.5 %>
                    min/Lesen
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<!-- upcoming tab -->
<div role="tabpanel" class="tab-pane py-3 mh-100" id="upcoming">
  <div class="row">
    <% @upcoming_articles.each do |upcoming_article| %>
      <div class="col-lg-3 my-2">
        <%= link_to upcoming_article do %>
          <div class="card topic-card justify-content-between">
            <div class="card-name pt-1 pb-4">
              <%= upcoming_article.title %>
            </div>
            <div class="card-bottom">
              <div class="card-progress">
                <div class="row mx-0 justify-content-between">
                  <div class="read-text">
                    Gelesen
                  </div>
                  <% if @read_articles.include?(upcoming_article) %>
                    <div class="progress-percentage">
                      100%
                    </div>
                    <progress class="w-100" value="100" max="100"></progress>
                  <% else %>
                    <div class="progress-percentage">
                      0%
                    </div>
                    <progress class="w-100" value="0" max="100"></progress>
                  <% end %>
                </div>
              </div>
              <div class="card-stats row justify-content-between">
                <div class="read-articles row mx-0 align-items-center">
                  <i class="material-icons-sharp stats-icon p-1">library_books</i>
                  1
                  Artikel
                </div>
                <div class="reading-time row mx-0 align-items-center">
                  <i class="material-icons-sharp stats-icon p-1">access_time</i>
                    <%= 1 * 2.5 %>
                    min/Lesen
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<!-- bookmarked tab -->
<div role="tabpanel" class="tab-pane py-3 mh-100" id="bookmarked">
  <div class="row">
    <% @bookmarked_articles.each do |bookmarked_article| %>
      <div class="col-lg-3 my-2">
        <%= link_to bookmarked_article do %>
          <div class="card topic-card justify-content-between">
            <div class="card-name pt-1 pb-4">
              <%= bookmarked_article.title %>
            </div>
            <div class="card-bottom">
              <div class="card-progress">
                <div class="row mx-0 justify-content-between">
                  <div class="read-text">
                    Gelesen
                  </div>
                  <% if @read_articles.include?(bookmarked_article) %>
                    <div class="progress-percentage">
                      100%
                    </div>
                    <progress class="w-100" value="100" max="100"></progress>
                  <% else %>
                    <div class="progress-percentage">
                      0%
                    </div>
                    <progress class="w-100" value="0" max="100"></progress>
                  <% end %>
                </div>
              </div>
              <div class="card-stats row justify-content-between">
                <div class="read-articles row mx-0 align-items-center">
                  <i class="material-icons-sharp stats-icon p-1">library_books</i>
                  1
                  Artikel
                </div>
                <div class="reading-time row mx-0 align-items-center">
                  <i class="material-icons-sharp stats-icon p-1">access_time</i>
                    <%= 1 * 2.5 %>
                    min/Lesen
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<!-- read tab -->
<div role="tabpanel" class="tab-pane py-3 mh-100" id="read">
  <div class="row">
    <% @read_articles.each do |read_article| %>
      <div class="col-lg-3 my-2">
        <%= link_to read_article do %>
          <div class="card topic-card justify-content-between">
            <div class="card-name pt-1 pb-4">
              <%= read_article.title %>
            </div>
            <div class="card-bottom">
              <div class="card-progress">
                <div class="row mx-0 justify-content-between">
                  <div class="read-text">
                    Gelesen
                  </div>
                  <% if @read_articles.include?(read_article) %>
                    <div class="progress-percentage">
                      100%
                    </div>
                    <progress class="w-100" value="100" max="100"></progress>
                  <% else %>
                    <div class="progress-percentage">
                      0%
                    </div>
                    <progress class="w-100" value="0" max="100"></progress>
                  <% end %>
                </div>
              </div>
              <div class="card-stats row justify-content-between">
                <div class="read-articles row mx-0 align-items-center">
                  <i class="material-icons-sharp stats-icon p-1">library_books</i>
                  1
                  Artikel
                </div>
                <div class="reading-time row mx-0 align-items-center">
                  <i class="material-icons-sharp stats-icon p-1">access_time</i>
                    <%= 1 * 2.5 %>
                    min/Lesen
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<% elsif current_user.admin? || current_user.author? %>
    <div class="row mt-5">
      <div class="col">
        <h1 class="display-4">Artikel</h1>
      </div>
    </div>
    <div class="row">
    <% @category.articles.each do |article| %>
      <div class="col-lg-3 my-2">
        <%= link_to article do %>
          <div class="card topic-card justify-content-between">
            <div class="card-name pt-1 pb-4">
              <%= article.title %>
              <%= fa_icon(:camera_retro, class: 'my-class', style: "position: absolute; top: 26px; right: 10px; color: green") unless article.draft? %>
            </div>
            <% if current_user.admin? %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-warning" %>
              <%= link_to "Delete", article_path(article), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      Kategorie bearbeiten
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= render "form", object: @category %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1 class="display-4">
        Neue Kategorie
      </h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= render "form", object: @category %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<% if current_user.student? %>
<div class="container header">
  <div class="my-3 h-100">
    <div class="row mh-100">
      <!-- breadcrumbs -->
      <div class="row mt-3 col-12 breadcrumbs ml-3">
        <%= link_to "Alle Lernfelder", topics_path %> &nbsp
        <div class="breadcrumb-arrow"> > </div> &nbsp
        <%= link_to @topic.name, @topic %> &nbsp
        <div class="breadcrumb-arrow"> > </div> &nbsp
        <%= @category.title %>
      </div>
      <!-- article header -->
      <div class="row col-12 justify-content-between">
        <div class="col-10 py-3">
          <h3><%= @category.title %></h3>
        </div>
        <!-- <div class="col-2">Grid/List View</div> -->
      </div>
      <div class="col-12 mh-100">
        <!-- tabs -->
        <ul class="nav nav-tabs justify-content-center" role="tablist">
          <li role="presentation" class="nav-item">
            <a href="#topic" aria-controls="topic" role="tab" data-toggle="tab" class="nav-link active">
              Alle
            </a>
          </li>
          <li role="presentation" class="nav-item">
            <a href="#upcoming" aria-controls="upcoming" role="tab" data-toggle="tab" class="nav-link">
              Offene
            </a>
          </li>
          <li role="presentation" class="nav-item">
            <a href="#bookmarked" aria-controls="bookmarked" role="tab" data-toggle="tab" class="nav-link">
              Markierte
            </a>
          </li>
          <li role="presentation" class="nav-item">
            <a href="#read" aria-controls="read" role="tab" data-toggle="tab" class="nav-link">
              Gelesene
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<% elsif current_user.admin? %>
  <div class="container mt-5">
    <%= render "pages/menu_create_records" %>
  </div>
<% end %>
<div class="container">
  <div class="tab-content mh-100">
    <%#= render 'list_view' %>
    <%= render 'grid_view' %>
    </div>
  </div>
</div>